package ai.pluggy.client.response;

import com.google.gson.annotations.SerializedName;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
public enum ExecutionErrorCode {

  @SerializedName("ALREADY_LOGGED_IN")
  ALREADY_LOGGED_IN("ALREADY_LOGGED_IN"),
  @SerializedName("INVALID_CREDENTIALS")
  INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
  @SerializedName("INVALID_CREDENTIALS_MFA")
  INVALID_CREDENTIALS_MFA("INVALID_CREDENTIALS_MFA"),
  @SerializedName("USER_INPUT_TIMEOUT")
  USER_INPUT_TIMEOUT("USER_INPUT_TIMEOUT"),
  @SerializedName("ACCOUNT_LOCKED")
  ACCOUNT_LOCKED("ACCOUNT_LOCKED"),
  @SerializedName("ACCOUNT_NEEDS_ACTION")
  ACCOUNT_NEEDS_ACTION("ACCOUNT_NEEDS_ACTION"),
  @SerializedName("ACCOUNT_CREDENTIALS_RESET")
  ACCOUNT_CREDENTIALS_RESET("ACCOUNT_CREDENTIALS_RESET"),
  @SerializedName("USER_NOT_SUPPORTED")
  USER_NOT_SUPPORTED("USER_NOT_SUPPORTED"),
  @SerializedName("USER_AUTHORIZATION_PENDING")
  USER_AUTHORIZATION_PENDING("USER_AUTHORIZATION_PENDING"),
  @SerializedName("USER_AUTHORIZATION_NOT_GRANTED")
  USER_AUTHORIZATION_NOT_GRANTED("USER_AUTHORIZATION_NOT_GRANTED"),
  @SerializedName("USER_AUTHORIZATION_REVOKED")
  USER_AUTHORIZATION_REVOKED("USER_AUTHORIZATION_REVOKED"),
  @SerializedName("SITE_NOT_AVAILABLE")
  SITE_NOT_AVAILABLE("SITE_NOT_AVAILABLE"),
  @SerializedName("CONNECTION_ERROR")
  CONNECTION_ERROR("CONNECTION_ERROR"),
  @SerializedName("UNEXPECTED_ERROR")
  UNEXPECTED_ERROR("UNEXPECTED_ERROR");

  @Getter
  private String value;

}