package ai.pluggy.client.response;

import com.google.gson.annotations.SerializedName;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
public enum ExecutionStatus {

  @SerializedName("SUCCESS")
  SUCCESS("SUCCESS"),
  @SerializedName("PARTIAL_SUCCESS")
  PARTIAL_SUCCESS("PARTIAL_SUCCESS"),
  @SerializedName("ERROR")
  ERROR("ERROR"),
  @SerializedName("CREATING")
  CREATING("CREATING"),
  @SerializedName("CREATE_ERROR")
  CREATE_ERROR("CREATE_ERROR"),
  @SerializedName("CREATED")
  CREATED("CREATED"),
  @SerializedName("LOGIN_IN_PROGRESS")
  LOGIN_IN_PROGRESS("LOGIN_IN_PROGRESS"),
  @SerializedName("WAITING_USER_INPUT")
  WAITING_USER_INPUT("WAITING_USER_INPUT"),
  @SerializedName("WAITING_USER_ACTION")
  WAITING_USER_ACTION("WAITING_USER_ACTION"),
  @SerializedName("LOGIN_MFA_IN_PROGRESS")
  LOGIN_MFA_IN_PROGRESS("LOGIN_MFA_IN_PROGRESS"),
  @SerializedName("ACCOUNTS_IN_PROGRESS")
  ACCOUNTS_IN_PROGRESS("ACCOUNTS_IN_PROGRESS"),
  @SerializedName("TRANSACTIONS_IN_PROGRESS")
  TRANSACTIONS_IN_PROGRESS("TRANSACTIONS_IN_PROGRESS"),
  @SerializedName("PAYMENT_DATA_IN_PROGRESS")
  PAYMENT_DATA_IN_PROGRESS("PAYMENT_DATA_IN_PROGRESS"),
  @SerializedName("CREDITCARDS_IN_PROGRESS")
  CREDITCARDS_IN_PROGRESS("CREDITCARDS_IN_PROGRESS"),
  @SerializedName("INVESTMENTS_IN_PROGRESS")
  INVESTMENTS_IN_PROGRESS("INVESTMENTS_IN_PROGRESS"),
  @SerializedName("INVESTMENTS_TRANSACTIONS_IN_PROGRESS")
  INVESTMENTS_TRANSACTIONS_IN_PROGRESS("INVESTMENTS_TRANSACTIONS_IN_PROGRESS"),
  @SerializedName("OPPORTUNITIES_IN_PROGRESS")
  OPPORTUNITIES_IN_PROGRESS("OPPORTUNITIES_IN_PROGRESS"),
  @SerializedName("IDENTITY_IN_PROGRESS")
  IDENTITY_IN_PROGRESS("IDENTITY_IN_PROGRESS"),
  @SerializedName("PORTFOLIO_IN_PROGRESS")
  PORTFOLIO_IN_PROGRESS("PORTFOLIO_IN_PROGRESS"),
  @SerializedName("INCOME_REPORTS_IN_PROGRESS")
  INCOME_REPORTS_IN_PROGRESS("INCOME_REPORTS_IN_PROGRESS"),
  @SerializedName("MOVE_SECURITY_IN_PROGRESS")
  MOVE_SECURITY_IN_PROGRESS("MOVE_SECURITY_IN_PROGRESS"),
  @SerializedName("LOANS_IN_PROGRESS")
  LOANS_IN_PROGRESS("LOANS_IN_PROGRESS"),
  @SerializedName("ACQUIRER_OPERATIONS_IN_PROGRESS")
  ACQUIRER_OPERATIONS_IN_PROGRESS("ACQUIRER_OPERATIONS_IN_PROGRESS"),
  @SerializedName("BENEFITS_IN_PROGRESS")
  BENEFITS_IN_PROGRESS("BENEFITS_IN_PROGRESS"),
  @SerializedName("FINISHED")
  FINISHED("FINISHED"),
  @SerializedName("MERGE_ERROR")
  MERGE_ERROR("MERGE_ERROR"),
  @SerializedName("ALREADY_LOGGED_IN")
  ALREADY_LOGGED_IN("ALREADY_LOGGED_IN"),
  @SerializedName("INVALID_CREDENTIALS")
  INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
  @SerializedName("INVALID_CREDENTIALS_MFA")
  INVALID_CREDENTIALS_MFA("INVALID_CREDENTIALS_MFA"),
  @SerializedName("USER_INPUT_TIMEOUT")
  USER_INPUT_TIMEOUT("USER_INPUT_TIMEOUT"),
  @SerializedName("ACCOUNT_LOCKED")
  ACCOUNT_LOCKED("ACCOUNT_LOCKED"),
  @SerializedName("ACCOUNT_NEEDS_ACTION")
  ACCOUNT_NEEDS_ACTION("ACCOUNT_NEEDS_ACTION"),
  @SerializedName("ACCOUNT_CREDENTIALS_RESET")
  ACCOUNT_CREDENTIALS_RESET("ACCOUNT_CREDENTIALS_RESET"),
  @SerializedName("USER_NOT_SUPPORTED")
  USER_NOT_SUPPORTED("USER_NOT_SUPPORTED"),
  @SerializedName("USER_AUTHORIZATION_PENDING")
  USER_AUTHORIZATION_PENDING("USER_AUTHORIZATION_PENDING"),
  @SerializedName("USER_AUTHORIZATION_NOT_GRANTED")
  USER_AUTHORIZATION_NOT_GRANTED("USER_AUTHORIZATION_NOT_GRANTED"),
  @SerializedName("USER_AUTHORIZATION_REVOKED")
  USER_AUTHORIZATION_REVOKED("USER_AUTHORIZATION_REVOKED"),
  @SerializedName("SITE_NOT_AVAILABLE")
  SITE_NOT_AVAILABLE("SITE_NOT_AVAILABLE"),
  @SerializedName("CONNECTION_ERROR")
  CONNECTION_ERROR("CONNECTION_ERROR"),
  @SerializedName("UNEXPECTED_ERROR")
  UNEXPECTED_ERROR("UNEXPECTED_ERROR");

  @Getter
  private String value;

}
