# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java + Maven CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PLUGGY_CLIENT_ID: "ccd5b9be-3be6-45fe-9512-5907f1619db0"
      PLUGGY_BASE_URL: "https://dev-pluggy-api.herokuapp.com"
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check Test Env Variables
      run: echo PLUGGY_CLIENT_ID '$PLUGGY_CLIENT_ID' PLUGGY_BASE_URL '$PLUGGY_BASE_URL'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Integration Tests
      run: mvn -B verify --file pom.xml
